export const ROUTES = {
  HOME: '/',
  DESTINATION: {
    INDEX: '/destination',
    SEARCH: '/destination/search',
  },
  TOUR: {
    INDEX: '/tour',
    SEARCH: '/tour/search',
    DETAIL: '/tour/:id',
  },
  ROOM: {
    INDEX: '/room',
    SEARCH: '/room/search',
    DETAIL: '/room/:id',
  },
  DASHBOARD: {
    INDEX: '/dashboard',
    PROFILE: '/dashboard/profile',
    CHANGE_PASSWORD: '/dashboard/change-password',
    BOOKINGS: '/dashboard/bookings',
    INVOICES: '/dashboard/invoices',
    REVIEWS: '/dashboard/reviews',
    WISHLIST: '/dashboard/wishlist',
    FAVORITES: '/dashboard/favorites',
    ROOM_BOOKINGS: '/dashboard/room-bookings',
    ROOM_BOOKINGS_DETAIL: '/dashboard/room-bookings/:id',
    ROOM_INVOICES: '/dashboard/room-invoices',
    ROOM_REVIEWS: '/dashboard/room-reviews',
    ROOM_WISHLIST: '/dashboard/room-wishlist',
    TOUR_BOOKINGS: '/dashboard/tour-bookings',
    TOUR_INVOICES: '/dashboard/tour-invoices',
    TOUR_REVIEWS: '/dashboard/tour-reviews',
    TOUR_WISHLIST: '/dashboard/tour-wishlist',
  },
  LOGIN: '/login',
  REGISTER: '/register',
  BOOKING_PAYMENT: '/bookings/:id/payment',
};
